In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [14]:
x = np.ones(3)
print(x)

[1. 1. 1.]


## Q#2: Create y array with elements equal to 0.

In [15]:
y = np.zeros(3)
print(y)

[0. 0. 0.]


## Q#3: Add x and y arrays.

In [16]:
x+y

array([1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [30]:
print(f'dimensions = {x.ndim}, shape = {x.shape}, size = {len(x)}, type = {x.dtype}')

dimensions = 1, shape = (3,), size = 3, type = float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [85]:
w = np.array([[11, 12], [13, 14], [15, 16]], ndmin = 2)
print(w)

[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [87]:
z = np.arange(start = 1, stop = 4)
print(z)

[1 2 3]


## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [88]:
z = z.reshape(-1, 1)

In [89]:
print(z)

[[1]
 [2]
 [3]]


In [90]:
newArray = np.hstack((w, z))
print(newArray)

[[11 12  1]
 [13 14  2]
 [15 16  3]]


## Q#8: Print all elements of "newArray" using the loop.

In [58]:
for row in newArray:
    for elements in row:
        print(elements)

11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [59]:
newArray = newArray[::-1, ::-1]
print(newArray)

[[ 3 16 15]
 [ 2 14 13]
 [ 1 12 11]]


## Q#10: Decrement all elements of "newArray" with 1.

In [60]:
newArray - 1

array([[ 2, 15, 14],
       [ 1, 13, 12],
       [ 0, 11, 10]])

## Q#11: Find smallest and biggest values in "newArray".

In [38]:
newArray.max()

16

## Q#12: Print the first row of "newArray" using indexing.

In [39]:
print(newArray[0])

[ 3 16 15]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [79]:
print(newArray)


[[ 3]
 [16]
 [15]
 [ 2]
 [14]
 [13]
 [ 1]
 [12]
 [11]]


In [75]:
for pos in newArray:
    print(pos == 12)    

[False False False]
[False False False]
[False  True False]


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [71]:
for pos in newArray:
     print(pos == 0)

[False False False]
[False False False]
[False False False]


## Q#15: Change the shape of "newArray" to (9,1).

In [77]:
newArray = newArray.reshape(9, 1)
print(newArray)

[[ 3]
 [16]
 [15]
 [ 2]
 [14]
 [13]
 [ 1]
 [12]
 [11]]


## Q#16: Change the shape of "newArray" to (3,2).

In [91]:
newArray = newArray.reshape(3, 2)
print(newArray)

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉