In [264]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [267]:
x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [270]:
y = np.zeros(10)
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Q#3: Add x and y arrays.

In [273]:
z = x + y
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [276]:
print(type(x))
print(x.shape)
print(x.size)
print(x.ndim)
print(x.dtype)

<class 'numpy.ndarray'>
(10,)
10
1
float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [279]:
w = np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [282]:
z = np.array([1,2,3])
#or
z = np.arange(1, 4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray

In [285]:
z.shape

(3,)

In [287]:
w.shape

(3, 2)

In [289]:
z = z.reshape(-1,1)
z.shape

(3, 1)

In [291]:
newArray = np.hstack((z,w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [294]:
for raw in newArray:
    for i in raw:
        print(i)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [304]:
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

In [308]:
newArray = newArray[::-1, ::-1]
newArray

array([[16, 15,  3],
       [14, 13,  2],
       [12, 11,  1]])

## Q#10: Decrement all elements of "newArray" with 1.

In [310]:
newArray = newArray - 1
newArray

array([[15, 14,  2],
       [13, 12,  1],
       [11, 10,  0]])

## Q#11: Find smallest and biggest values in "newArray".

In [312]:
newArray.max()

15

In [314]:
newArray.min()

0

## Q#12: Print the first row of "newArray" using indexing.

In [316]:
newArray[0,]

array([15, 14,  2])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [318]:
newArray[1,1]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [226]:
num_0 = newArray[2, 2]
num_13 = newArray[1, 0] 
print(num_0)
print(num_13)

0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [238]:
newArray.reshape(9,1)

array([[15],
       [14],
       [ 2],
       [13],
       [12],
       [ 1],
       [11],
       [10],
       [ 0]])

## Q#16: Change the shape of "newArray" to (3,2).

#The answer: 
As we can see the original array have 3 raws and 3 cloumn with 9 elements , therfore it is impossible to reshape it without removing 3 elements.

In [240]:
newArray

array([[15, 14,  2],
       [13, 12,  1],
       [11, 10,  0]])

# Well Done 🎉