# Q1: Import numpy library

In [1]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [2]:
sequence = np.linspace(0, 1, 15)
print(sequence)

[0.         0.07142857 0.14285714 0.21428571 0.28571429 0.35714286
 0.42857143 0.5        0.57142857 0.64285714 0.71428571 0.78571429
 0.85714286 0.92857143 1.        ]


# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [8]:
array1 = np.array([1.1, 2.1, 3.1])
array2 = np.array([4.1, 5.1, 6.1])
array3 = np.array([7.1, 8.1, 9.1])
array4 = np.array([10.1, 11.1, 12.1])

# Combine them into a 3-D array
array_3d = np.array([[array1, array2], [array3, array4]])

print(array_3d)
print("Shape of the array:", array_3d.shape)

[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]
Shape of the array: (2, 2, 3)


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [9]:
# Array's type
array_type = type(array_3d)
# Array's elements datatype
elements_datatype = array_3d.dtype
# Array's shape
array_shape = array_3d.shape
# Array's size
array_size = array_3d.size
# Array's dimension
array_dimension = array_3d.ndim

print("Array's type:", array_type)
print("Array's elements datatype:", elements_datatype)
print("Array's shape:", array_shape)
print("Array's size:", array_size)
print("Array's dimension:", array_dimension)

Array's type: <class 'numpy.ndarray'>
Array's elements datatype: float64
Array's shape: (2, 2, 3)
Array's size: 12
Array's dimension: 3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [10]:
array_4d = array_3d.reshape(2, 2, 1, 3)

print("New array's dimension:", array_4d.ndim)
print("New array's shape:", array_4d.shape)
print(array_4d)

New array's dimension: 4
New array's shape: (2, 2, 1, 3)
[[[[ 1.1  2.1  3.1]]

  [[ 4.1  5.1  6.1]]]


 [[[ 7.1  8.1  9.1]]

  [[10.1 11.1 12.1]]]]


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [11]:
array_4d_int = array_4d.astype(int)
print(array_4d_int)

[[[[ 1  2  3]]

  [[ 4  5  6]]]


 [[[ 7  8  9]]

  [[10 11 12]]]]


In [12]:
array_4d_int.dtype

dtype('int32')

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [13]:
for element in np.nditer(array_4d_int):
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [14]:
print(array_4d_int[1, 0, 0, 1])

8


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [15]:
print(array_4d_int[0, 1, 0, 1:3])

[5 6]


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [16]:
indices = np.where(array_4d_int == 8)
print("Indices where the number 8 is located:", indices)

Indices where the number 8 is located: (array([1], dtype=int64), array([0], dtype=int64), array([0], dtype=int64), array([1], dtype=int64))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [17]:
reshaped_array = array_4d_int.reshape(2, 3, 2)

print(reshaped_array)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [18]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
joined_array = np.concatenate((arr1, arr2))

print(joined_array)

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [21]:
joined_array_axis = np.concatenate((arr1, arr2), axis=1)
print(joined_array_axis)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [24]:
split_arrays = np.split(joined_array, 2, axis=1)

for i, array in enumerate(split_arrays):
    print(f"Array {i+1}:\n{array}\n")


Array 1:
[['A' 'B']
 ['E' 'F']]

Array 2:
[['C' 'D']
 ['G' 'H']]

