In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [2]:
x=np.ones(5)
x

array([1., 1., 1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [3]:
y=np.zeros(5)
y

array([0., 0., 0., 0., 0.])

## Q#3: Add x and y arrays.

In [4]:
result=x+y
result

array([1., 1., 1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [5]:
# dimension x and y array
print('x dimension: ',x.ndim)
print('y dimension: ',y.ndim)

x dimension:  1
y dimension:  1


In [6]:
# shape of x and y array
print('x shape: ',x.shape)
print('y shape: ',y.shape)

x shape:  (5,)
y shape:  (5,)


In [7]:
#size of x and y array
print('x size: ',x.size)
print('y size: ',y.size)

x size:  5
y size:  5


In [8]:
#type of x and y array
print('type of x array: ',type(x))
print('type of y array: ',type(y))

type of x array:  <class 'numpy.ndarray'>
type of y array:  <class 'numpy.ndarray'>


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [9]:
w=np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [10]:
z=np.array([1,2,3])
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [11]:
z_2d = z.reshape(-1,1)

In [12]:
newArray=np.hstack((w,z_2d))
newArray

array([[11, 12,  1],
       [13, 14,  2],
       [15, 16,  3]])

## Q#8: Print all elements of "newArray" using the loop.

In [13]:
for i in newArray:
    for j in i:
        print(j)
   

11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [14]:
newArray = newArray[::-1, ::-1]
newArray 

array([[ 3, 16, 15],
       [ 2, 14, 13],
       [ 1, 12, 11]])

## Q#10: Decrement all elements of "newArray" with 1.

In [15]:
newArray = newArray - 1
newArray

array([[ 2, 15, 14],
       [ 1, 13, 12],
       [ 0, 11, 10]])

## Q#11: Find smallest and biggest values in "newArray".

In [16]:
smallest_value = np.min(newArray )
largest_value = np.max(newArray )

print("Smallest value:", smallest_value)
print("Largest value:", largest_value)

Smallest value: 0
Largest value: 15


## Q#12: Print the first row of "newArray" using indexing.

In [17]:
newArray

array([[ 2, 15, 14],
       [ 1, 13, 12],
       [ 0, 11, 10]])

In [18]:

print("First row of newArray:", newArray[0])

First row of newArray: [ 2 15 14]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [19]:
newArray[1,2]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [20]:
print("frist number: ",newArray[2,0])
print("second number:", newArray[1, 1]) 

frist number:  0
second number: 13


## Q#15: Change the shape of "newArray" to (9,1).

In [21]:
newArray = newArray.reshape((9, 1))
newArray

array([[ 2],
       [15],
       [14],
       [ 1],
       [13],
       [12],
       [ 0],
       [11],
       [10]])

## Q#16: Change the shape of "newArray" to (3,2).

In [25]:
#------------------there is ValueError: cannot reshape array of size 9 into shape (3,2) when i use (reshape)------------------
'''
newArray = newArray.reshape((3, 2))
newArray
'''
#after searching, i found that can be solved by(resize)
newArray = np.resize(newArray, (3, 2))
print(newArray)

[[ 2 15]
 [14  1]
 [13 12]]


In [26]:
newArray.shape

(3, 2)

# Well Done 🎉