In [206]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [207]:
# write your code here ^_^

x=np.ones(3)
print("x =",x)


x = [1. 1. 1.]


## Q#2: Create y array with elements equal to 0.

In [208]:
# write your code here ^_^
y=np.zeros(3)
print("y =",y)



y = [0. 0. 0.]


## Q#3: Add x and y arrays.



In [209]:
# write your code here ^_^

add_arr=x+y
add_arr





array([1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [210]:
# write your code here ^_^
print("Dimension is :" ,x.ndim)
print("Shape is :" ,x.shape)
print("Size is :" ,x.size)
print("Type is :" ,x.dtype)

Dimension is : 1
Shape is : (3,)
Size is : 3
Type is : float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [211]:
# write your code here ^_^
w=np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [212]:
# write your code here ^_^
z = np.arange(1, 4)
z


array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [213]:
# write your code here ^_^
z=z.reshape(-1,1) #reshape from r=1 c=3 to r=3 c=1
z



array([[1],
       [2],
       [3]])

In [214]:
newArray=np.hstack((z,w)) #newArray r=3 c=3
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [215]:
# write your code here ^_^
for i in newArray:
    print(i)

[ 1 11 12]
[ 2 13 14]
[ 3 15 16]


## Q#9: Reverse the columns and rows of "newArray".

In [216]:
# write your code here ^_^
revrs_array = np.flip(newArray, axis=(0, 1))    #method 1 used flip function 
reverse_array = newArray[::-1, ::-1]     #method 2 used slicing 

reverse_array


array([[16, 15,  3],
       [14, 13,  2],
       [12, 11,  1]])

## Q#10: Decrement all elements of "newArray" with 1.

In [217]:
# write your code here ^_^
newArray =newArray-1
newArray


array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [218]:
# write your code here ^_^

s=newArray.min()
b=newArray.max()
print("smallset",s)
print("biggest",b)



smallset 0
biggest 15


## Q#12: Print the first row of "newArray" using indexing.

In [219]:
# write your code here ^_^
print(newArray[0])

[ 0 10 11]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [220]:
# write your code here ^_^
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

In [221]:
print(newArray[1,1]) #(r,c) 

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [222]:
# write your code here ^_^
newArray


array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

In [223]:
print(newArray[0,0])    #(r,c)
print(newArray[1,2])   #

0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [224]:
# write your code here ^_^

changed_shaped=newArray.reshape(9,1)
changed_shaped


array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [225]:
#

# Well Done 🎉