# Q1: Import numpy library

In [252]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [253]:
float_num = np.linspace(0,15,15)
print(float_num)
f = float_num.size
print(f'number of elements in array : {f}')

[ 0.          1.07142857  2.14285714  3.21428571  4.28571429  5.35714286
  6.42857143  7.5         8.57142857  9.64285714 10.71428571 11.78571429
 12.85714286 13.92857143 15.        ]
number of elements in array : 15


# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [254]:
up_to_me_Array = np.linspace(1.1,12.1,12)
up_to_me_Array = up_to_me_Array.reshape(2,2,3)
up_to_me_Array

array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [255]:
print("type of array elements:")
print(type(up_to_me_Array))
print("\nData type of array elements:")
print(up_to_me_Array.dtype)
print("\nShape of the array:")
print(up_to_me_Array.shape)
print("\nNumber of dimensions:")
print(up_to_me_Array.ndim)


type of array elements:
<class 'numpy.ndarray'>

Data type of array elements:
float64

Shape of the array:
(2, 2, 3)

Number of dimensions:
3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [256]:
new_array = np.reshape(up_to_me_Array, (3, 1, 4, 1))
print(new_array.ndim)
print(new_array.shape)
print(new_array)

4
(3, 1, 4, 1)
[[[[ 1.1]
   [ 2.1]
   [ 3.1]
   [ 4.1]]]


 [[[ 5.1]
   [ 6.1]
   [ 7.1]
   [ 8.1]]]


 [[[ 9.1]
   [10.1]
   [11.1]
   [12.1]]]]


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [257]:
int_array = newArray.astype(int)
print(int_array)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [258]:
for i in np.nditer(int_array):
    print(i, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [259]:
int_array[0,1,3]

8

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [260]:
print(int_array[0][1][0:2])

[5 6]


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [261]:
np.where(int_array == 8)

(array([0]), array([1]), array([3]))

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [262]:
int_array = int_array.reshape(2,3,2)
int_array

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [263]:
array_1 = np.array([['A', 'B'], ['E', 'F']])
array_2 = np.array([['C', 'D'], ['G', 'H']])
joined_array = np.concatenate((array_1, array_2))
print(joined_array)

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [264]:
joined_axis = np.concatenate((array_1, array_2), axis=1)
print(joined_axis)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [265]:
testArr1, testArr2 = np.hsplit(joined_axis, 2)
testArr1
testArr2

array([['C', 'D'],
       ['G', 'H']], dtype='<U1')