# Q1: Import numpy library

In [5]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [14]:
x = np.linspace(1, 16,15)
x

array([ 1.        ,  2.07142857,  3.14285714,  4.21428571,  5.28571429,
        6.35714286,  7.42857143,  8.5       ,  9.57142857, 10.64285714,
       11.71428571, 12.78571429, 13.85714286, 14.92857143, 16.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [28]:
arr = np.array([[[1.1, 2.1, 3.1], [4.1, 5.1, 6.1]], [[7.1, 8.1, 9.1], [10.1, 11.1, 12.1]]])
arr

array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [30]:
type(arr)

numpy.ndarray

In [32]:
arr.dtype

dtype('float64')

In [34]:
arr.shape

(2, 2, 3)

In [36]:
arr.size

12

In [38]:
arr.ndim

3

# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [56]:
newArr = np.reshape(arr, (4,3))
newArr

array([[ 1.1,  2.1,  3.1],
       [ 4.1,  5.1,  6.1],
       [ 7.1,  8.1,  9.1],
       [10.1, 11.1, 12.1]])

In [58]:
newArr.shape

(4, 3)

# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [60]:
arrType = newArr.astype('i')
arrType

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [62]:
for i in np.nditer(arrType):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [66]:
arrType[2][1]

8

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [74]:
arrType[1][1:]

array([5, 6], dtype=int32)

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [84]:
arrType

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)

In [82]:
search = np.where(arrType==8) 
print(search) 

(array([2]), array([1]))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [94]:
arrType.reshape(-1,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]], dtype=int32)

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [98]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

In [100]:
arr = np.concatenate((arr1, arr2))
arr

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [112]:
arr_index = np.concatenate((arr1, arr2), axis=1)
arr_index

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [120]:
arr_split = np.split(arr, 2, axis=1)
arr_split

[array([['A', 'B'],
        ['E', 'F']], dtype='<U1'),
 array([['C', 'D'],
        ['G', 'H']], dtype='<U1')]