# Q1: Import numpy library

In [191]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [192]:
print(np.linspace(0 ,1, 15)) 

[0.         0.07142857 0.14285714 0.21428571 0.28571429 0.35714286
 0.42857143 0.5        0.57142857 0.64285714 0.71428571 0.78571429
 0.85714286 0.92857143 1.        ]


# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [193]:
Array3d = np.array([[[1.1 , 4.1 , 7.1],[4.1 , 5.1 , 6.1]] , [[7.1 , 8.1 , 9.1],[10.1 , 11.1 , 12.1]]])
print(Array3d)

[[[ 1.1  4.1  7.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [194]:
print("shape" , Array3d.shape)
print("dimension" , Array3d.ndim)
print("size" , Array3d.size)
print("data type" , Array3d.dtype)
print("type" , type(Array3d))

shape (2, 2, 3)
dimension 3
size 12
data type float64
type <class 'numpy.ndarray'>


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [195]:
Array4d = np.array([np.dstack(Array3d)])
print(Array4d)

[[[[ 1.1  7.1]
   [ 4.1  8.1]
   [ 7.1  9.1]]

  [[ 4.1 10.1]
   [ 5.1 11.1]
   [ 6.1 12.1]]]]


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [196]:
intArray = Array4d.astype('i')
intArray

array([[[[ 1,  7],
         [ 4,  8],
         [ 7,  9]],

        [[ 4, 10],
         [ 5, 11],
         [ 6, 12]]]], dtype=int32)

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [197]:
for x in np.nditer(intArray):
    print(x)

1
7
4
8
7
9
4
10
5
11
6
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [198]:
print(intArray[0:1, 0:1, 1:2, 1:2])

[[[[8]]]]


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [199]:
print(intArray[0:1, 1:2, 1:3 , 0:1])

[[[[5]
   [6]]]]


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [200]:
a = np.where(intArray == 8)
print(intArray[a])

[8]


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [201]:
print(intArray.reshape(1,2,3,2)) 

[[[[ 1  7]
   [ 4  8]
   [ 7  9]]

  [[ 4 10]
   [ 5 11]
   [ 6 12]]]]


# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [202]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

conArray = np.concatenate((arr1,arr2))
conArray

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [203]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

np.concatenate((arr1,arr2) , axis=1)

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [204]:
split1 , split2 = np.array_split(conArray ,2, axis =1)
print("Array 1 with 4 arrays\n",split1,"\narray 2 with 4 arrays\n", split2 )

Array 1 with 4 arrays
 [['A']
 ['E']
 ['C']
 ['G']] 
array 2 with 4 arrays
 [['B']
 ['F']
 ['D']
 ['H']]
