In [152]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [153]:
x = np.ones((3,3),dtype=int)
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


## Q#2: Create y array with elements equal to 0.

In [154]:
y = np.zeros((3,3),dtype=int)
print(y)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


## Q#3: Add x and y arrays.

In [155]:
add_arr = np.add(x, y)  
print(add_arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [156]:
print(x)
print("type of array elements:")
print(type(x))
print("\nShape of the array:")
print(x.shape)
print("\nNumber of dimensions:")
print(x.ndim)
print("\nTotal number of elements:")
print(x.size)
print("\nData type of array elements:")
print(x.dtype)


[[1 1 1]
 [1 1 1]
 [1 1 1]]
type of array elements:
<class 'numpy.ndarray'>

Shape of the array:
(3, 3)

Number of dimensions:
2

Total number of elements:
9

Data type of array elements:
int64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [157]:
w = np.array([
             [11,12],
             [13,14],
             [15,16]
             ])
print(w)

[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [158]:
z = np.array([[1,2,3]])
print(z)

[[1 2 3]]


## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [159]:
z  = z.transpose()
newArray = np.hstack((w, z))
newArray

array([[11, 12,  1],
       [13, 14,  2],
       [15, 16,  3]])

## Q#8: Print all elements of "newArray" using the loop.

In [160]:
for i in newArray.flat:
    print(i)


11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [161]:
newArray = newArray.transpose()
print(newArray)

[[11 13 15]
 [12 14 16]
 [ 1  2  3]]


## Q#10: Decrement all elements of "newArray" with 1.

In [162]:
newArray -= 1
print(newArray)

[[10 12 14]
 [11 13 15]
 [ 0  1  2]]


## Q#11: Find smallest and biggest values in "newArray".

In [163]:
min_value = newArray.min()
max_value = newArray.max()
print(f'smalest value is :{min_value}')
print(f'smalest value is :{max_value}')



smalest value is :0
smalest value is :15


## Q#12: Print the first row of "newArray" using indexing.

In [164]:
print(newArray[0])

[10 12 14]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [165]:
print(newArray[0][1])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [166]:
print(newArray[1,1])
print(newArray[2,0])

13
0


## Q#15: Change the shape of "newArray" to (9,1).

In [167]:
newArray = newArray.reshape(9,1)
print(newArray)
newArray.shape

[[10]
 [12]
 [14]
 [11]
 [13]
 [15]
 [ 0]
 [ 1]
 [ 2]]


(9, 1)

## Q#16: Change the shape of "newArray" to (3,2).

# NOTE:
## we can't reshape this array to (3,2) because the array size is equal to 9, but we can reshape it to (3,3)
#### You can try it, but you will receive this error
```py
ValueError: cannot reshape array of size 9 into shape (3,2)
```

In [168]:
newArray = newArray.reshape(3,3)
print(newArray)
newArray.shape

[[10 12 14]
 [11 13 15]
 [ 0  1  2]]


(3, 3)

# Well Done 🎉