# Q1: Import numpy library

In [236]:
# write your code here ^_^
import numpy as np



# Q2: Generate a sequence of 15 floats using linspace() function

In [237]:
# write your code here ^_^
sequence = np.linspace(0,15,15) #linespace(p1=init,p2=end,p3=number of element)
sequence


array([ 0.        ,  1.07142857,  2.14285714,  3.21428571,  4.28571429,
        5.35714286,  6.42857143,  7.5       ,  8.57142857,  9.64285714,
       10.71428571, 11.78571429, 12.85714286, 13.92857143, 15.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [238]:
# write your code here ^_^
arr_3d=np.array([[[1.1,2.1,3.1],[4.1,5.1,6.1],[7.1,8.1,9.1],[10.1,11.1,12.1]]]) #3 Square bracket 
arr_3d

array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1],
        [ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [239]:
# write your code here ^_^
print("Array type :",type(arr_3d) )
print("Array element datatype :",arr_3d.dtype )
print("Array shape :" , arr_3d.shape)
print("Array size :" , arr_3d.size)
print("Array dimension :", arr_3d.ndim,"D")



Array type : <class 'numpy.ndarray'>
Array element datatype : float64
Array shape : (1, 4, 3)
Array size : 12
Array dimension : 3 D


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [240]:
# write your code here ^_^
arr_4d = arr_3d[None, :]    #[indx1=Add a new dimension with size is 1 ,indx2=2 to : to keep same values]
arr_4d

array([[[[ 1.1,  2.1,  3.1],
         [ 4.1,  5.1,  6.1],
         [ 7.1,  8.1,  9.1],
         [10.1, 11.1, 12.1]]]])

# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [241]:
# write your code here ^_^
changed_arr= arr_4d.astype('i')
changed_arr

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]], dtype=int32)

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [242]:
# write your code here ^_^
 
for x in np.nditer(changed_arr):    #nditer used to iterate object in numpy array
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [243]:
# write your code here ^_^
changed_arr


array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]], dtype=int32)

In [244]:
print(changed_arr[0,0,2,1]) 



8


In [245]:
print(changed_arr[0]) #from 4d to 3d


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [246]:
print(changed_arr[0,0]) #from 3d to 2d

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [247]:
print(changed_arr[0,0,2]) #select the row wheres 8 is found,we found 8 in number 3  but in index equal 2 

[7 8 9]


In [248]:
print(changed_arr[0,0,2,1]) #select the index number 1 

8


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [249]:
changed_arr

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]], dtype=int32)

In [250]:
print(changed_arr[0,0,1,1])

5


In [251]:
# write your code here ^_^
print(changed_arr[0,0,1,2])

6


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [252]:
# write your code here ^_^
changed_arr

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]], dtype=int32)

In [253]:
find=np.where(changed_arr==8) 
find


(array([0], dtype=int64),
 array([0], dtype=int64),
 array([2], dtype=int64),
 array([1], dtype=int64))

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [254]:
# write your code here ^_^
changed_arr


array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]], dtype=int32)

In [255]:
r_changed_arr = changed_arr.reshape(2, 3, 2)
print(r_changed_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [256]:
# write your code here ^_^
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
join_arr=np.concatenate((arr1,arr2))
print(join_arr)

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [257]:
# write your code here ^_^
q12=np.concatenate((arr1,arr2),axis=1)
print(q12)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [258]:
# write your code here ^_^
arr_split=np.split(join_arr,2,axis=1)
print(arr_split)

[array([['A'],
       ['E'],
       ['C'],
       ['G']], dtype='<U1'), array([['B'],
       ['F'],
       ['D'],
       ['H']], dtype='<U1')]
