In [14]:
import numpy as np
import random

## Q#1: Create x array with elements equal to 1.

In [4]:
# write your code here ^_^
x = np.ones(5)
x

array([1., 1., 1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [5]:
# write your code here ^_^
y = np.zeros(5)
y

array([0., 0., 0., 0., 0.])

## Q#3: Add x and y arrays.

In [6]:
# write your code here ^_^
x+y

array([1., 1., 1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [10]:
# write your code here ^_^
x.shape
x.ndim
x.size
x.dtype

dtype('float64')

## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [13]:
# write your code here ^_^
w = np.array([[11,12], [13,14], [15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [26]:
# write your code here ^_^
z = np.array([1,2,3])
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [47]:
# write your code here ^_^
newArray = np.hstack((w, z.reshape(-1, 1)))
newArray

array([[11, 12,  1],
       [13, 14,  2],
       [15, 16,  3]])

## Q#8: Print all elements of "newArray" using the loop.

In [48]:
# write your code here ^_^
for i in newArray:
    print(i)

[11 12  1]
[13 14  2]
[15 16  3]


## Q#9: Reverse the columns and rows of "newArray".

In [49]:
# write your code here ^_^
newArray = newArray.T
newArray

array([[11, 13, 15],
       [12, 14, 16],
       [ 1,  2,  3]])

## Q#10: Decrement all elements of "newArray" with 1.

In [50]:
# write your code here ^_^
newArray = newArray - 1
newArray


array([[10, 12, 14],
       [11, 13, 15],
       [ 0,  1,  2]])

## Q#11: Find smallest and biggest values in "newArray".

In [52]:
# write your code here ^_^
newArray.max()
newArray.min()


0

## Q#12: Print the first row of "newArray" using indexing.

In [55]:
# write your code here ^_^
newArray[0]

array([10, 12, 14])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [57]:
# write your code here ^_^
newArray[0,1]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [59]:
# write your code here ^_^
newArray[2,0]
newArray[1,1]

0

## Q#15: Change the shape of "newArray" to (9,1).

In [60]:
# write your code here ^_^
newArray = newArray.reshape(9,1)
newArray

array([[10],
       [12],
       [14],
       [11],
       [13],
       [15],
       [ 0],
       [ 1],
       [ 2]])

## Q#16: Change the shape of "newArray" to (3,2).

In [61]:
# write your code here ^_^
newArray = newArray.reshape(3,2)
newArray
#cannot reshape array of size 9 into shape (3,2) it can't be done because they have diff sizes 

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉