# Q1: Import numpy library

In [104]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [107]:
sequence = np.linspace(0, 15, 15)
print(sequence)

[ 0.          1.07142857  2.14285714  3.21428571  4.28571429  5.35714286
  6.42857143  7.5         8.57142857  9.64285714 10.71428571 11.78571429
 12.85714286 13.92857143 15.        ]


# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [110]:
arr1 = np.array([1.1,	2.1,	3.1])
print(arr1)

print()

arr2 = np.array([4.1,	5.1,	6.1])
print(arr2)

print()

arr3 = np.array([7.1,	8.1,	9.1])
print(arr3)

print()

arr4 = np.array([10.1,	11.1,	12.1])
print(arr4)

print()
print("the 3-D array")

arr5 = np.array([[arr1, arr2], [arr3, arr4]])
print(arr5)
print()
print(arr5.shape)
print(arr5.ndim)


[1.1 2.1 3.1]

[4.1 5.1 6.1]

[7.1 8.1 9.1]

[10.1 11.1 12.1]

the 3-D array
[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]

(2, 2, 3)
3


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [113]:
print(type(arr5))
print(arr5.dtype)
print(arr5.shape)
print(arr5.size)
print(arr5.ndim)

<class 'numpy.ndarray'>
float64
(2, 2, 3)
12
3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [116]:
arr6 = arr5.reshape(2, 2, 1, 3)
print(arr6)
print()
print(arr6.shape)
print(arr6.ndim)

[[[[ 1.1  2.1  3.1]]

  [[ 4.1  5.1  6.1]]]


 [[[ 7.1  8.1  9.1]]

  [[10.1 11.1 12.1]]]]

(2, 2, 1, 3)
4


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [119]:
arr7 = arr6.astype((int))
print(arr7)

[[[[ 1  2  3]]

  [[ 4  5  6]]]


 [[[ 7  8  9]]

  [[10 11 12]]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [122]:
for i in np.nditer(arr7):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [125]:
print(arr7[1, 0, 0, 1])

8


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [128]:
print(arr7[0, 1, 0, 1:])

[5 6]


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [131]:
find = np.where(arr7 == 8)
print(find)

(array([1], dtype=int64), array([0], dtype=int64), array([0], dtype=int64), array([1], dtype=int64))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [134]:
arr8 = arr7.reshape(2, 3, 2)
print(arr8)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [137]:
arr1s = np.array([['A', 'B'], ['E', 'F']])
arr2s = np.array([['C', 'D'], ['G', 'H']])
print(arr1s)
print(arr2s)

print()###########

arr3s =  np.concatenate((arr1s, arr2s))
print(arr3s)

[['A' 'B']
 ['E' 'F']]
[['C' 'D']
 ['G' 'H']]

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [140]:
arr4s =  np.concatenate((arr1s, arr2s), axis = 1)
print(arr4s)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [143]:
SplitArray = np.split(arr3s, 2, axis=1)
print(SplitArray)



[array([['A'],
       ['E'],
       ['C'],
       ['G']], dtype='<U1'), array([['B'],
       ['F'],
       ['D'],
       ['H']], dtype='<U1')]


In [147]:
# Musab Alsobhi