In [92]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [93]:
x = np.ones(1)
print(x)

[1.]


## Q#2: Create y array with elements equal to 0.

In [94]:
y = np.zeros(1)
print(y)

[0.]


## Q#3: Add x and y arrays.

In [95]:
print(x + y) 

[1.]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [96]:
print("shape" , x.shape)
print("dimension" , x.ndim)
print("size" , x.size)
print("Data type" , x.dtype)
print("type" , type(x))

shape (1,)
dimension 1
size 1
Data type float64
type <class 'numpy.ndarray'>


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [97]:
w = np.array([[11 , 12] , [13 , 14] , [15 , 16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [98]:
z = np.array([[1 , 2 , 3]])
z 

array([[1, 2, 3]])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [99]:
print(w.shape , z.T.shape)

(3, 2) (3, 1)


In [100]:
newArray = np.hstack((z.T, w))
newArray 

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [101]:
for x in newArray :
    for y in x :
        print(y)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [102]:
for x in np.fliplr(newArray)[::-1]:
    print(x)

[16 15  3]
[14 13  2]
[12 11  1]


## Q#10: Decrement all elements of "newArray" with 1.

In [103]:
newArray1 = newArray -1
print(newArray1)

[[ 0 10 11]
 [ 1 12 13]
 [ 2 14 15]]


## Q#11: Find smallest and biggest values in "newArray".

In [104]:
print("thw smallest number is : " ,newArray.min())
print("thw biggest number is : " ,newArray.max())

thw smallest number is :  1
thw biggest number is :  16


## Q#12: Print the first row of "newArray" using indexing.

In [105]:
print('First row: ', newArray[0])

First row:  [ 1 11 12]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [106]:
print(newArray[0][2])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [107]:
print(newArray1[0][0])
print(newArray1[1][2])

0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [108]:
newArray1 =  newArray.reshape(9,1)
newArray1 

array([[ 1],
       [11],
       [12],
       [ 2],
       [13],
       [14],
       [ 3],
       [15],
       [16]])

## Q#16: Change the shape of "newArray" to (3,2).

In [81]:
print(newArray1.reshape(3,2))

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉