# Q1: Import numpy library

In [43]:
# write your code here ^_^
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [9]:
# write your code here ^_^
a = np.linspace(0, 1, 15)
a

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [20]:
# write your code here ^_^
arr1  = np.array([1.1, 2.1, 3.1])
arr2  = np.array([4.1, 5.1, 6.1])
arr3  = np.array([7.1, 8.1, 9.1])
arr4  = np.array([10.1, 11.1, 12.1])
arr1234 = np.array(([[arr1, arr2], [arr3, arr4]]))
arr1234.shape


(2, 2, 3)

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [40]:
# write your code here ^_^
type(arr1234)
arr1234.dtype
arr1234.shape
arr1234.size
arr1234.ndim


3

# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [56]:
# write your code here ^_^
arr1234_4d = np.reshape(arr1234, (4, 3))
arr1234_4d


2

# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [57]:
# write your code here ^_^
arr_int = arr1234_4d.astype(int)
arr_int

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [58]:
# write your code here ^_^
arr_nd =  np.nditer(arr_int)

# Iterate over the array and print each element
for i in arr_nd:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [79]:
# write your code here ^_^
arr_int[2,1]

8

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [82]:
# write your code here ^_^
arr_int[1,1]
arr_int[1,2]

6

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [90]:
# write your code here ^_^
path = np.where(arr_int == 8)

path

(array([2], dtype=int64), array([1], dtype=int64))

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [95]:
# write your code here ^_^
arr_int_3d= arr_int.reshape(2,2,3)
arr_int_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [110]:
# write your code here ^_^
arr11 = np.array([['A', 'B'], ['E', 'F']])
arr22 = np.array([['C', 'D'], ['G', 'H']])
arr_join= np.concatenate((arr11,arr22), axis=0)
arr_join

#Q12.1
arr_join2= np.concatenate((arr11,arr22))
arr_join2

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [102]:
# write your code here ^_^
arr_join3= np.concatenate((arr11,arr22), axis=1)
arr_join3

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [111]:
# write your code here ^_^
arr_split= np.split(arr_join2,4, axis=1)
arr_split


ValueError: array split does not result in an equal division