In [14]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [15]:
x = np.ones(3)

## Q#2: Create y array with elements equal to 0.

In [16]:
y = np.zeros(3)

## Q#3: Add x and y arrays.

In [17]:
x + y

array([1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [18]:
print(f"Dimension: {x.ndim}")
print(f"Shape: {x.shape}")
print(f"Size: {x.size}")
print(f"Type: {x.dtype}")

Dimension: 1
Shape: (3,)
Size: 3
Type: float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [19]:
w = np.array([[11, 12], [13, 14], [15, 16]])

In [20]:
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [21]:
z = np.arange(1, 4)

In [22]:
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [23]:
newArray = np.hstack((w, z.reshape(3, 1)))

In [24]:
newArray

array([[11, 12,  1],
       [13, 14,  2],
       [15, 16,  3]])

## Q#8: Print all elements of "newArray" using the loop.

In [25]:
for data in np.nditer(newArray):
    print(data)

11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [26]:
newArray = newArray.T

In [27]:
newArray

array([[11, 13, 15],
       [12, 14, 16],
       [ 1,  2,  3]])

## Q#10: Decrement all elements of "newArray" with 1.

In [28]:
newArray = newArray - 1
newArray

array([[10, 12, 14],
       [11, 13, 15],
       [ 0,  1,  2]])

## Q#11: Find smallest and biggest values in "newArray".

In [29]:
np.min(newArray)

0

In [30]:
np.max(newArray)

15

## Q#12: Print the first row of "newArray" using indexing.

In [31]:
newArray[0]

array([10, 12, 14])

In [32]:
newArray

array([[10, 12, 14],
       [11, 13, 15],
       [ 0,  1,  2]])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [33]:
newArray[0][1]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [34]:
newArray[2][0]

0

In [35]:
newArray[1][1]

13

## Q#15: Change the shape of "newArray" to (9,1).

In [36]:
newArray = newArray.reshape(9, 1)
newArray

array([[10],
       [12],
       [14],
       [11],
       [13],
       [15],
       [ 0],
       [ 1],
       [ 2]])

## Q#16: Change the shape of "newArray" to (3,2).

In [37]:
# we cannot reshape newArray to (3,2) directly due to it having more elements than the shape (3,2) takes
# Therefore we need to drop some data so it fits the shape needed, we will choose the column with the lowest values
# to return it to the original 2 arrays used.
#
# we will:
#       1. reshape it into (3,3) from (9,1)
#       2. transpose it so the lowest values is the last column
#       3. drop the last column to achieve shape (3,2)

# Reshaping to (3,3)
newArray = newArray.reshape(3, 3)

In [38]:
newArray

array([[10, 12, 14],
       [11, 13, 15],
       [ 0,  1,  2]])

In [39]:
# Transopsing
newArray = newArray.T

In [40]:
newArray

array([[10, 11,  0],
       [12, 13,  1],
       [14, 15,  2]])

In [41]:
# removing the last column (lowest values column after transposing)
newArray = np.delete(newArray, 2, axis=1)
newArray

array([[10, 11],
       [12, 13],
       [14, 15]])

In [42]:
newArray.shape

(3, 2)

# Well Done 🎉