# Q1: Import numpy library

In [1]:
# write your code here ^_^
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [2]:
# write your code here ^_^
np.linspace(0, 15, 15) # 0 the start, 15 the stoping elements, 15 the sequence interval number

array([ 0.        ,  1.07142857,  2.14285714,  3.21428571,  4.28571429,
        5.35714286,  6.42857143,  7.5       ,  8.57142857,  9.64285714,
       10.71428571, 11.78571429, 12.85714286, 13.92857143, 15.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [3]:
# write your code here ^_^
# creation
arr = np.array([[[1.1, 2.1, 3.1], [4.1, 5.1, 6.1]], [[7.1, 8.1, 9.1], [10.1, 11.1, 12.1]]])
print(arr)
print(arr.shape) # 2 the outermost dimension [] brackets, 2 the 2D brackets, 3 is each of 3D which are the elements

[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]
(2, 2, 3)


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [10]:
# write your code here ^_^
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.size)
print(arr.ndim)

<class 'numpy.ndarray'>
float64
(1, 4, 3)
12
3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes.
- Print the new array's dimention and shape.

In [7]:
# write your code here ^_^
arr2 = arr.reshape(2, 2, 3, 1)
print(arr2)
print(arr2.ndim)
print(arr2.shape)


[[[[ 1.1]
   [ 2.1]
   [ 3.1]]

  [[ 4.1]
   [ 5.1]
   [ 6.1]]]


 [[[ 7.1]
   [ 8.1]
   [ 9.1]]

  [[10.1]
   [11.1]
   [12.1]]]]
4
(2, 2, 3, 1)


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes.
- Print the new array.

In [8]:
# write your code here ^_^
arr3 = arr2.astype(int)
arr3

array([[[[ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6]]],


       [[[ 7],
         [ 8],
         [ 9]],

        [[10],
         [11],
         [12]]]])

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [9]:
# write your code here ^_^
# nditer iterates over elements in the array
for i in np.nditer(arr3):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [54]:
# write your code here ^_^
print(arr3[1:,0:1,1:2])

[[[[8]]]]


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [10]:
# write your code here ^_^
print(arr3[0:1, 1:, 1:2])
print(arr3[0:1, 1:, 2:3])


[[[[5]]]]
[[[[6]]]]


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [11]:
# write your code here ^_^
np.where(arr3==8)

(array([1]), array([0]), array([1]), array([0]))

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [12]:
# write your code here ^_^
arr3.reshape(2, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis

In [13]:
# write your code here ^_^
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

join_arrays = np.concatenate((arr1, arr2))
join_arrays

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1

In [14]:
# write your code here ^_^
join_arrays = np.concatenate((arr1, arr2), axis=1)
join_arrays

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays.
Note: use the same array from Q12.1

In [15]:
# write your code here ^_^
sp = np.array_split(join_arrays, 2, axis=1)
sp

[array([['A', 'B'],
        ['E', 'F']], dtype='<U1'),
 array([['C', 'D'],
        ['G', 'H']], dtype='<U1')]