In [2]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [3]:
# write your code here ^_^
x = np.ones(6)
x

array([1., 1., 1., 1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [4]:
# write your code here ^_^
y = np.zeros(6)
y

array([0., 0., 0., 0., 0., 0.])

## Q#3: Add x and y arrays.

In [5]:
# write your code here ^_^
add_arr = x + y
add_arr

array([1., 1., 1., 1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [6]:
# write your code here ^_^
print(x.ndim)  # dimension of an array
print(x.shape)  # shape of an array , 5 rows and one column, the dimension n x m
print(x.size)  # total number of elements in the array
print(type(x))


1
(6,)
6
<class 'numpy.ndarray'>


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [7]:
# write your code here ^_^
w = np.array([[11, 12], [13, 14], [15, 16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [8]:
# write your code here ^_^
z = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]]) # added because when combining we must have same dimension of rows
z

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [10]:
# write your code here ^_^
newArray = np.hstack((z, w))
newArray

array([[ 1,  2,  3, 11, 12],
       [ 1,  2,  3, 13, 14],
       [ 1,  2,  3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [11]:
# write your code here ^_^
for i in newArray:
  print(i)

[ 1  2  3 11 12]
[ 1  2  3 13 14]
[ 1  2  3 15 16]


## Q#9: Reverse the columns and rows of "newArray".

In [23]:
# write your code here ^_^
newArray = np.transpose(newArray)
print(newArray)

[[ 0  0  0]
 [ 1  1  1]
 [ 2  2  2]
 [10 12 14]
 [11 13 15]]


## Q#10: Decrement all elements of "newArray" with 1.

In [24]:
# write your code here ^_^
newArray = newArray - 1
newArray

array([[-1, -1, -1],
       [ 0,  0,  0],
       [ 1,  1,  1],
       [ 9, 11, 13],
       [10, 12, 14]])

## Q#11: Find smallest and biggest values in "newArray".

In [25]:
# write your code here ^_^
small = np.min(newArray)
small

-1

In [26]:
big = np.max(newArray)
big

14

## Q#12: Print the first row of "newArray" using indexing.

In [27]:
# write your code here ^_^
print(newArray[0])

[-1 -1 -1]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [29]:
# write your code here ^_^
print(newArray[4][1])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [33]:
# write your code here ^_^
print(newArray[1][0] , newArray[1][1], newArray[1][2])
print(newArray[3][2])

0 0 0
13





## Q#15: Change the shape of "newArray" to (9,1).

In [35]:
# write your code here ^_^
# 9 number of rows, and 1 number of columns
# Explanation: here we cannot reshape the array because the size is not compatible to be adjusted to (9,1)
newArray.reshape(9,1)

ValueError: cannot reshape array of size 15 into shape (9,1)

## Q#16: Change the shape of "newArray" to (3,2).

In [ ]:
# write your code here ^_^
newArray.reshape(3,2) # i think the reason is that we cannot reshape the dimensions same as the Q 15

ValueError: cannot reshape array of size 2 into shape (3,2)

# Well Done 🎉